name: Shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
          npm -v 
  #     - name: python Command
  #       run: |
  #         import platform
  #         print(platform.processor())
  #       shell: python 
  # run-on-windows-runner: 
  #   runs-on: windows-latest
  #   steps:
  #     - name: Output Directory in in defualt shell, powershell
  #       run: Get-Location
  #     - name: Output the directory from bash
  #       run: pwd
  #       shell: bash 



  